### ISSUE TITLE
Is the package maintained anymore?

### ISSUE THREAD

**Issue by aytunch** [octomato/preload_page_view#38]
@octomato are you planning on supporting this awesome package?

**Comment by octomato** [comment]
Hi @aytunch I'm planning to merge my code to Flutter official view pager widget. I got some feedback and testing an edge case in iOS.

**Comment by aytunch** [comment]
@octomato this is great news. The functionality this package offers is definitely needed by all Flutter developers. Do you have an estimate on the date?
If there is a PR you have opened, or open in the future, can you please link it here so we can follow?
Best regards.
