### ISSUE TITLE
i want to load page with use preloadPagesCount

### ISSUE THREAD

**Issue by singlakaran** [octomato/preload_page_view#6]
i want to load a page when i want and want to use preloadPagesCount.
please help @octomato

**Comment by Neil-Gu-Bose** [comment]
Hey @singlakaran Could you please clarify the requirements?
`Want to load a page when I want` is that means you want a controller to start or stop preload jobs?

**Comment by octomato** [comment]
Hey @singlakaran Could you please provide more information?
`Want to load a page when i want ` is that means you want have a controller to star or stop preload jobs?

**Comment by octomato** [comment]
Close this ticket because no more information
